common:
	@sh components/common.sh

frontend: common
	@sudo sh components/frontend.sh

mongo: common
	@sudo sh components/mongo.sh

catalogue: common
	@sh components/catalogue.sh

redis: common
	@sudo sh components/redis.sh

user: common
	@sudo sh components/user.sh

cart: common
	@sh components/cart.sh

catalogue: common
	@sudo sh components/catalogue.sh

shipping: common
	@sudo sh components/shipping.sh

rabbitmq: common
	@sudo sh components/rabbitmq.sh

payment: common
	@sh compoennts/payment.sh