common:
	@sh components/common.sh

frontend:
	@sudo sh components/frontend.sh

mongo:
	@sudo sh components/mongo.sh

catalogue:
	@sudo sh components/catalogue.sh

redis:
	@sudo sh components/redis.sh

user:
	@sudo sh components/user.sh

cart:
	@sudo sh components/cart.sh

catalogue:
	@sudo sh components/catalogue.sh

shipping:
	@sudo sh components/shipping.sh

rabbitmq:
	@sudo sh components/rabbitmq.sh

payment:
	@sh compoennts/payment.sh